/**
 * Taxonomy — the task classification knowledge base.
 *
 * Each entry carries weighted signals (kw/ph/re) used by the classifier plus
 * domain defaults (expert role, must-have requirements, default techniques,
 * default output format, risk flags). Templates read these defaults and adapt
 * them dynamically rather than copying blindly.
 *
 * Signals are deliberately distinctive: single words match on word boundaries,
 * phrases match on substrings. Awkward synonyms live in `kw`/`ph`, never in regex.
 */

export const TAXONOMY = [
  {
    id: 'general-qa', label: 'General Q&A', group: 'knowledge',
    kw: ['question', 'answer', 'explain', 'what', 'how', 'why', 'difference'],
    ph: ['tell me about', 'what is', 'how does', 'explain how', 'i want to know'],
    role: 'knowledgeable domain expert',
    must: ['targeted question', 'assumed knowledge level'], tech: ['role', 'structuredOutput'],
    fmt: 'markdown',
  },
  {
    id: 'research', label: 'Research', group: 'knowledge',
    kw: ['research', 'literature', 'paper', 'papers', 'study', 'studies', 'sources', 'references', 'survey', 'state-of-the-art'],
    ph: ['literature review', 'research question', 'what does the literature', 'find sources', 'academic sources', 'evidence base'],
    role: 'research analyst', needsSources: true,
    must: ['research question', 'scope', 'source quality bar', 'recency window', 'evidence handling'],
    tech: ['role', 'stepBack', 'retrieval', 'researchSynthesizeVerify', 'verification', 'rubric'],
    fmt: 'structured-report',
  },
  {
    id: 'web-research', label: 'Web research', group: 'knowledge',
    kw: ['online', 'web', 'internet', 'google', 'search', 'browse', 'blogs', 'forums', 'news'],
    ph: ['search the web', 'look it up online', 'current information', 'latest news', 'from the internet', 'up to date'],
    role: 'research analyst with web access', needsSources: true,
    must: ['time window', 'source quality', 'cross-checking rule', 'citation format'],
    tech: ['role', 'retrieval', 'factCheck', 'verification'],
    fmt: 'structured-report',
  },
  {
    id: 'academic', label: 'Academic work', group: 'academic', academic: true,
    kw: ['academic', 'university', 'assignment', 'coursework', 'dissertation', 'thesis', 'seminar', 'professor', 'lecturer', 'grading', 'rubric', 'citations', 'apa', 'mla', 'ieee', 'harvard'],
    ph: ['my assignment', 'final year project', 'course assignment', 'term paper', 'academic writing', 'university level', 'grading criteria', 'word essay', 'for my coursework', 'for my assignment', 'for my course', 'with references', 'mark scheme', 'according to my rubric'],
    role: 'academic writing and research specialist',
    must: ['academic level', 'citation style', 'length tolerance', 'originality rule', 'marking criteria'],
    tech: ['role', 'rubric', 'constraints', 'verification', 'examples'],
    fmt: 'academic', needsSources: true,
  },
  {
    id: 'learning', label: 'Learning & study', group: 'academic',
    kw: ['learn', 'learning', 'understand', 'study', 'studying', 'tutorial', 'course', 'beginner', 'basics', 'fundamentals', 'prerequisites', 'roadmap'],
    ph: ['teach me', 'help me learn', 'from scratch', 'explain like i am a beginner', 'i am new to', 'step by step course'],
    role: 'patient expert tutor',
    must: ['current knowledge level', 'target level', 'depth', 'practice element'],
    tech: ['role', 'socratic', 'decomposition', 'examples', 'generateEvaluateImprove'],
    fmt: 'markdown',
  },
  {
    id: 'exam-prep', label: 'Exam preparation', group: 'academic', academic: true,
    kw: ['exam', 'exams', 'revision', 'revise', 'revising', 'cram', 'cramming', 'quiz', 'quizzes', 'mcq', 'mcqs', 'viva', 'midterm', 'finals', 'mock', 'flashcards', 'syllabus', 'marks', 'grade'],
    ph: ['exam preparation', 'prepare for my exam', 'revise for', 'revising for', 'study for my exam', 'past paper', 'past papers', 'practice questions', 'revision notes', 'exam questions', 'keep forgetting', 'i keep failing'],
    role: 'exam coach and subject examiner',
    must: ['syllabus scope', 'exam format', 'difficulty level', 'answer key or marking scheme'],
    tech: ['role', 'rubric', 'fewShot', 'generateEvaluateImprove'],
    fmt: 'markdown',
  },
  {
    id: 'writing', label: 'Writing', group: 'communication',
    kw: ['write', 'writing', 'essay', 'article', 'blog', 'post', 'report', 'letter', 'story', 'draft', 'prose', 'copy', 'document'],
    ph: ['write me', 'write a', 'draft a', 'compose a', 'help me write'],
    role: 'professional writer and editor',
    must: ['audience', 'purpose', 'tone', 'structure', 'length'],
    tech: ['role', 'constraints', 'examples', 'draftCritiqueRevise'],
    fmt: 'prose',
  },
  {
    id: 'rewriting', label: 'Rewriting & paraphrasing', group: 'communication',
    kw: ['rewrite', 'paraphrase', 'reword', 'rephrase', 'humanize', 'simplify', 'condense'],
    ph: ['rewrite this', 'in my own words', 'make it sound human', 'different wording', 'reword this'],
    role: 'expert editor',
    must: ['source text', 'preservation rules', 'target voice', 'invariance constraints'],
    tech: ['role', 'constraints', 'examples', 'draftCritiqueRevise'],
    fmt: 'prose',
  },
  {
    id: 'editing', label: 'Editing & proofreading', group: 'communication',
    kw: ['edit', 'editing', 'proofread', 'proofreading', 'grammar', 'typo', 'typos', 'punctuation', 'spelling', 'clarity', 'redline', 'copyedit'],
    ph: ['check my grammar', 'proofread this', 'fix the writing', 'clean up this text'],
    role: 'copy editor and proofreader',
    must: ['source text', 'edit level (light/standard/heavy)', 'output form (clean text vs tracked changes)'],
    tech: ['role', 'structuredOutput', 'verification', 'rubric'],
    fmt: 'structured-report',
  },
  {
    id: 'translation', label: 'Translation', group: 'communication',
    kw: ['translate', 'translation', 'localize', 'localisation', 'localization', 'bilingual', 'subtitle', 'subtitles'],
    ph: ['translate this', 'into spanish', 'in french', 'from english to'],
    role: 'professional translator and localisation specialist',
    must: ['source language', 'target language', 'register', 'handling of proper nouns', 'output purity rule'],
    tech: ['role', 'constraints', 'examples', 'verification'],
    fmt: 'plain',
  },
  {
    id: 'summarization', label: 'Summarisation', group: 'knowledge',
    kw: ['summarize', 'summarise', 'summary', 'tl;dr', 'tldr', 'abstract', 'condense', 'gist', 'key points', 'takeaways'],
    ph: ['summarize this', 'key points', 'in a nutshell', 'main takeaways', 'short version'],
    role: 'analyst skilled at compression',
    must: ['source text', 'compression target', 'what must survive', 'fidelity rule'],
    tech: ['role', 'constraints', 'structuredOutput', 'verification'],
    fmt: 'bullets',
  },
  {
    id: 'analysis', label: 'Analysis', group: 'knowledge',
    kw: ['analyse', 'analyze', 'analysis', 'evaluate', 'assess', 'assessment', 'critique', 'examine', 'breakdown', 'implications'],
    ph: ['analyze this', 'deep dive', 'what does this mean', 'critical analysis', 'pros and cons'],
    role: 'senior analyst in the relevant domain',
    must: ['object of analysis', 'analytical lens', 'depth', 'evidence standard'],
    tech: ['role', 'decomposition', 'multiPerspective', 'rubric', 'verification'],
    fmt: 'structured-report',
  },
  {
    id: 'comparison', label: 'Comparison', group: 'knowledge',
    kw: ['compare', 'comparison', 'versus', 'vs', 'better', 'alternative', 'alternatives', 'trade-offs', 'tradeoffs'],
    ph: ['which is better', 'compare and contrast', 'differences between', 'pros and cons of', 'should i use x or y'],
    role: 'impartial technical/domain evaluator',
    must: ['options being compared', 'criteria', 'weighting', 'verdict rule'],
    tech: ['comparative', 'rubric', 'structuredOutput', 'verification'],
    fmt: 'table',
  },
  {
    id: 'decision', label: 'Decision making', group: 'life',
    kw: ['decide', 'decision', 'choose', 'choice', 'pick', 'dilemma', 'stuck', 'should', 'whether', 'undecided'],
    ph: ['help me decide', 'i cannot decide', 'should i', 'what should i do', 'weigh my options'],
    role: 'decision analyst (decision-support specialist)',
    must: ['options', 'criteria and weights', 'constraints', 'uncertainty handling', 'recommendation with flip conditions'],
    tech: ['decisionFramework', 'multiPerspective', 'premortem', 'structuredOutput'],
    fmt: 'decision-brief',
  },
  {
    id: 'planning', label: 'Planning', group: 'life',
    kw: ['plan', 'planning', 'schedule', 'timeline', 'roadmap', 'milestones', 'itinerary', 'strategy', 'phases'],
    ph: ['make a plan', 'plan out', 'step by step plan', 'how do i get from', 'project plan'],
    role: 'experienced planner in the relevant domain',
    must: ['start state', 'end state', 'time horizon', 'resources', 'unknowns'],
    tech: ['role', 'decomposition', 'planExecute', 'premortem'],
    fmt: 'plan',
  },
  {
    id: 'coding', label: 'Coding', group: 'engineering',
    kw: ['code', 'coding', 'program', 'programming', 'function', 'script', 'implement', 'implementation', 'library', 'sdk', 'python', 'javascript', 'java', 'cpp', 'typescript', 'golang', 'rust', 'php', 'sql', 'react', 'vue', 'node', 'api'],
    ph: ['write code', 'write a function', 'help me code', 'implement this', 'build a script', 'fix the code'],
    role: 'senior software engineer',
    must: ['language and version', 'runtime/environment', 'input and output contract', 'error handling expectations', 'dependency policy'],
    tech: ['role', 'constraints', 'structuredOutput', 'examples', 'verification', 'edgeCases'],
    fmt: 'code',
  },
  {
    id: 'debugging', label: 'Debugging', group: 'engineering',
    kw: ['bug', 'debug', 'debugging', 'error', 'errors', 'exception', 'crash', 'crashes', 'stacktrace', 'traceback', 'fails', 'failing', 'broken', 'issue', 'regression', 'segfault', 'throws', 'throwing', 'undefined', 'null', 'nan', 'hang', 'hangs', 'leak', 'timeout'],
    ph: ['not working', 'throws an error', 'why does this fail', 'find the bug', 'does not work', 'error message', 'cannot read propert', 'is undefined', 'undefined is not', 'keeps failing', 'keeps crashing', 'works locally but', 'only fails when'],
    role: 'senior debugging specialist',
    must: ['symptom', 'expected vs actual', 'reproduction steps', 'environment', 'error output'],
    tech: ['role', 'diagnosePlanExecuteValidate', 'hypothesisTesting', 'verification', 'edgeCases'],
    fmt: 'structured-report',
  },
  {
    id: 'architecture', label: 'Software architecture', group: 'engineering',
    kw: ['architecture', 'architect', 'system design', 'scalability', 'microservices', 'monolith', 'design pattern', 'patterns', 'modular', 'trade-off'],
    ph: ['system design', 'design an architecture', 'how should i structure', 'scale to', 'design pattern for'],
    role: 'principal software architect',
    must: ['requirements and scale targets', 'constraints', 'non-functional requirements', 'explicit trade-off reasoning'],
    tech: ['role', 'decomposition', 'comparative', 'premortem', 'verification'],
    fmt: 'structured-report',
  },
  {
    id: 'data-analysis', label: 'Data analysis', group: 'data',
    kw: ['data', 'dataset', 'csv', 'excel', 'spreadsheet', 'statistics', 'statistical', 'correlation', 'regression', 'pandas', 'tableau', 'insights', 'metrics'],
    ph: ['analyze my data', 'find patterns', 'statistical test', 'what do these numbers mean', 'data driven'],
    role: 'data analyst / applied statistician',
    must: ['data description', 'question being answered', 'assumptions about data quality', 'statistical honesty rules'],
    tech: ['role', 'extractAnalyzeGenerate', 'verification', 'structuredOutput'],
    fmt: 'structured-report',
  },
  {
    id: 'mathematics', label: 'Mathematics', group: 'science',
    kw: ['math', 'maths', 'mathematics', 'equation', 'integral', 'derivative', 'algebra', 'calculus', 'geometry', 'proof', 'theorem', 'probability', 'matrix', 'vector'],
    ph: ['solve for', 'work out', 'show your working', 'prove that', 'step by step solution'],
    role: 'mathematician and careful problem solver',
    must: ['problem statement', 'required rigour', 'show-work rule', 'verification by substitution'],
    tech: ['role', 'decomposition', 'selfConsistency', 'verification', 'stepBack'],
    fmt: 'markdown',
  },
  {
    id: 'science', label: 'Science', group: 'science',
    kw: ['physics', 'chemistry', 'biology', 'scientific', 'hypothesis', 'experiment', 'laboratory', 'lab', 'reaction', 'genetics', 'thermodynamics'],
    ph: ['explain the science', 'scientific explanation', 'why does this happen physically'],
    role: 'scientist and science communicator',
    must: ['level of rigour', 'units and conventions', 'uncertainty honesty'],
    tech: ['role', 'stepBack', 'examples', 'verification'],
    fmt: 'markdown',
  },
  {
    id: 'engineering', label: 'Engineering (non-software)', group: 'engineering',
    kw: ['engineering', 'circuit', 'mechanical', 'electrical', 'cad', 'tolerance', 'component', 'specification', 'load', 'structural', 'pcb'],
    ph: ['engineering problem', 'design a circuit', 'mechanical design', 'component selection'],
    role: 'chartered engineer in the relevant discipline',
    must: ['standards to follow', 'safety factors', 'units', 'tolerances'],
    tech: ['role', 'constraints', 'premortem', 'verification'],
    fmt: 'structured-report',
  },
  {
    id: 'business', label: 'Business', group: 'business',
    kw: ['business', 'company', 'startup', 'revenue', 'profit', 'operations', 'strategy', 'market', 'customers', 'competitors', 'supply chain', 'b2b'],
    ph: ['business plan', 'business model', 'my company', 'go to market', 'business strategy'],
    role: 'management consultant with operating experience',
    must: ['business context', 'objective metric', 'constraints (budget/time/team)', 'assumption transparency'],
    tech: ['role', 'decomposition', 'comparative', 'premortem', 'structuredOutput'],
    fmt: 'structured-report',
  },
  {
    id: 'entrepreneurship', label: 'Entrepreneurship', group: 'business',
    kw: ['startup', 'founder', 'entrepreneur', 'mvp', 'funding', 'investor', 'pitch', 'validation', 'product-market', 'bootstrapping'],
    ph: ['start a business', 'validate my idea', 'pitch deck', 'raise funding', 'launch a product'],
    role: 'startup operator and venture advisor',
    must: ['stage and resources', 'constraints', 'evidence standard', 'what would falsify the idea'],
    tech: ['role', 'premortem', 'multiPerspective', 'premortem', 'verification'],
    fmt: 'structured-report',
  },
  {
    id: 'marketing', label: 'Marketing', group: 'business',
    kw: ['marketing', 'campaign', 'ads', 'advertising', 'brand', 'branding', 'funnel', 'conversion', 'audience', 'positioning', 'copywriting', 'email'],
    ph: ['marketing plan', 'ad copy', 'target audience', 'increase conversions', 'grow my audience'],
    role: 'growth marketer and copywriter',
    must: ['product/service', 'audience', 'channel', 'budget or scale', 'success metric'],
    tech: ['role', 'examples', 'branchSelect', 'rubric'],
    fmt: 'structured-report',
  },
  {
    id: 'seo', label: 'SEO', group: 'business',
    kw: ['seo', 'keywords', 'serp', 'backlinks', 'ranking', 'organic', 'meta description', 'schema markup', 'search console'],
    ph: ['rank higher', 'search engine optimisation', 'search engine optimization', 'keyword research', 'on page seo'],
    role: 'technical SEO strategist',
    must: ['site/topic context', 'target keywords or intent', 'search intent', 'constraints (white-hat only)'],
    tech: ['role', 'structuredOutput', 'rubric', 'verification'],
    fmt: 'structured-report',
  },
  {
    id: 'social-media', label: 'Social media', group: 'business',
    kw: ['instagram', 'linkedin', 'twitter', 'tiktok', 'youtube', 'hashtag', 'caption', 'reels', 'shorts', 'thread', 'social'],
    ph: ['social media post', 'caption for', 'viral post', 'content calendar', 'grow on'],
    role: 'social media strategist and copywriter',
    must: ['platform', 'audience', 'goal', 'brand voice', 'platform limits'],
    tech: ['role', 'examples', 'branchSelect'],
    fmt: 'structured-report',
  },
  {
    id: 'presentation', label: 'Presentations', group: 'communication',
    kw: ['presentation', 'slides', 'powerpoint', 'deck', 'keynote', 'pitch', 'speaker', 'seminar'],
    ph: ['slide deck', 'presentation outline', 'talk about', 'create slides', 'present to'],
    role: 'presentation designer and speechwriter',
    must: ['audience', 'duration', 'slide count', 'narrative arc', 'per-slide content limits'],
    tech: ['role', 'decomposition', 'structuredOutput', 'rubric'],
    fmt: 'slides',
  },
  {
    id: 'document', label: 'Document creation', group: 'communication',
    kw: ['document', 'doc', 'policy', 'sop', 'manual', 'handbook', 'specification', 'proposal', 'contract', 'template'],
    ph: ['write a document', 'create a report', 'official document', 'documentation for'],
    role: 'technical writer and documentation specialist',
    must: ['document type', 'audience', 'required sections', 'house style / template'],
    tech: ['role', 'structuredOutput', 'constraints', 'verification'],
    fmt: 'document',
  },
  {
    id: 'resume', label: 'Résumé / CV', group: 'career',
    kw: ['resume', 'cv', 'curriculum', 'ats', 'cover letter', 'portfolio', 'linkedin profile'],
    ph: ['my resume', 'cover letter', 'improve my cv', 'apply for a job', 'job application'],
    role: 'recruiter and career-writing specialist',
    must: ['target role', 'seniority', 'existing material', 'truthfulness rule', 'length limit'],
    tech: ['role', 'constraints', 'examples', 'rubric'],
    fmt: 'document',
  },
  {
    id: 'interview-prep', label: 'Interview preparation', group: 'career',
    kw: ['interview', 'interviews', 'hr round', 'technical round', 'mock interview', 'behavioural', 'behavioral', 'star method', 'screening'],
    ph: ['prepare for an interview', 'interview questions', 'mock interview', 'how do i answer'],
    role: 'interview coach and hiring manager',
    must: ['role and company', 'interview stage', 'candidate background', 'feedback loop'],
    tech: ['role', 'fewShot', 'rubric', 'roleplay'],
    fmt: 'structured-report',
  },
  {
    id: 'career', label: 'Career planning', group: 'career',
    kw: ['career', 'internship', 'promotion', 'salary', 'mentor', 'appraisal', 'resignation', 'notice period'],
    ph: ['career path', 'career advice', 'job offer', 'job hunt', 'should i switch', 'next step in my career', 'quit my job', 'change careers'],
    role: 'career strategist familiar with the industry',
    must: ['current situation', 'goal', 'constraints (time/money/location)', 'honest trade-offs'],
    tech: ['role', 'decisionFramework', 'decomposition', 'premortem'],
    fmt: 'decision-brief',
  },
  {
    id: 'productivity', label: 'Personal productivity', group: 'life',
    kw: ['productivity', 'procrastination', 'focus', 'habits', 'habit', 'routine', 'time management', 'burnout', 'motivation', 'distraction'],
    ph: ['stop procrastinating', 'manage my time', 'build a habit', 'stay focused', 'get organised'],
    role: 'behavioural coach grounded in evidence',
    must: ['current pattern', 'constraints', 'definition of done', 'realistic scope'],
    tech: ['role', 'planExecute', 'constraints', 'generateEvaluateImprove'],
    fmt: 'plan',
  },
  {
    id: 'project-management', label: 'Project management', group: 'business',
    kw: ['project', 'deadline', 'sprint', 'backlog', 'scope', 'stakeholder', 'agile', 'scrum', 'kanban', 'risk register', 'wbs'],
    ph: ['manage my project', 'project timeline', 'break this down', 'project risks', 'task breakdown'],
    role: 'delivery manager / project lead',
    must: ['deliverables', 'deadline', 'team and capacity', 'dependencies', 'risk handling'],
    tech: ['role', 'decomposition', 'premortem', 'structuredOutput'],
    fmt: 'plan',
  },
  {
    id: 'travel', label: 'Travel', group: 'life',
    kw: ['travel', 'trip', 'flight', 'flights', 'hotel', 'hostel', 'visa', 'itinerary', 'tourist', 'vacation', 'holiday', 'backpacking', 'sightseeing'],
    ph: ['plan a trip', 'trip to', 'travel to', 'things to do in', 'itinerary for', 'days in', 'nights in', 'flight to', 'visiting'],
    re: ['\\b\\d{1,2}[\\s-]?(?:day|night)s?\\s+(?:trip|in|to|itinerary)\\b'],
    role: 'seasoned travel planner for that region',
    must: ['origin and destination', 'dates/duration', 'budget', 'interests', 'pace', 'unverifiable-detail rule'],
    tech: ['role', 'structuredOutput', 'verification'],
    fmt: 'plan',
  },
  {
    id: 'finance', label: 'Finance', group: 'high-stakes', highStakes: true,
    kw: ['finance', 'financial', 'invest', 'investment', 'stocks', 'tax', 'taxes', 'loan', 'mortgage', 'savings', 'portfolio', 'interest rate', 'budgeting', 'salary', 'debt', 'retirement'],
    ph: ['my budget', 'monthly budget', 'financial advice', 'pay off my debt', 'tax question', 'manage my money', 'invest in', 'start investing', 'save for retirement'],
    role: 'financial analyst (educational, non-advisory)',
    must: ['full financial context', 'risk tolerance', 'jurisdiction', 'non-advisory disclaimer'],
    tech: ['role', 'decisionFramework', 'verification', 'constraints'],
    fmt: 'decision-brief',
  },
  {
    id: 'legal', label: 'Legal', group: 'high-stakes', highStakes: true,
    kw: ['legal', 'law', 'lawyer', 'contract', 'clause', 'compliance', 'gdpr', 'copyright', 'patent', 'trademark', 'liability', 'terms'],
    ph: ['is it legal', 'legal advice', 'my rights', 'review this contract', 'regulations for'],
    role: 'legal information analyst (not a licensed lawyer)',
    must: ['jurisdiction', 'facts', 'informational-only disclaimer', 'escalation trigger'],
    tech: ['role', 'verification', 'constraints', 'structuredOutput'],
    fmt: 'structured-report',
  },
  {
    id: 'health', label: 'Health & medicine', group: 'high-stakes', highStakes: true,
    kw: ['health', 'healthcare', 'medical', 'medicine', 'doctor', 'symptom', 'symptoms', 'diagnosis', 'treatment', 'medication', 'diet', 'nutrition', 'fitness', 'workout', 'mental health', 'anxiety', 'depression'],
    ph: ['is it normal', 'what should i do about', 'do i have', 'is it safe to take'],
    role: 'health information specialist (not a clinician)',
    must: ['symptom/fact detail', 'jurisdiction', 'red-flag escalation', 'non-diagnostic boundary'],
    tech: ['role', 'constraints', 'verification', 'structuredOutput'],
    fmt: 'structured-report',
  },
  {
    id: 'creative-writing', label: 'Creative writing', group: 'creative', creative: true,
    kw: ['story', 'novel', 'poem', 'poetry', 'fiction', 'character', 'characters', 'plot', 'narrative', 'screenplay', 'dialogue', 'worldbuilding', 'lyrics'],
    ph: ['write a story', 'short story', 'create a character', 'creative writing', 'write a poem'],
    role: 'award-winning fiction writer and story editor',
    must: ['genre', 'length', 'point of view', 'tense', 'voice/style', 'content boundaries'],
    tech: ['role', 'examples', 'constraints', 'branchSelect', 'draftCritiqueRevise'],
    fmt: 'prose',
  },
  {
    id: 'storytelling', label: 'Storytelling & narrative', group: 'creative', creative: true,
    kw: ['narrative', 'storytelling', 'arc', 'hook', 'plot', 'tension', 'pacing', 'three-act', 'hero'],
    ph: ['tell a story', 'story arc', 'narrative structure', 'make it compelling'],
    role: 'narrative designer',
    must: ['audience', 'medium', 'emotional target', 'structure model'],
    tech: ['role', 'decomposition', 'examples'],
    fmt: 'prose',
  },
  {
    id: 'image-generation', label: 'Image generation', group: 'media', media: 'image',
    kw: ['image', 'picture', 'illustration', 'photo', 'artwork', 'logo', 'poster', 'render', 'midjourney', 'dalle', 'dall-e', 'stable diffusion', 'flux', 'portrait', 'thumbnail', 'wallpaper'],
    ph: ['generate an image', 'create a picture', 'image prompt', 'make a logo', 'design a poster', 'an image of', 'make me an image', 'a picture of', 'make an image', 'image of a', 'draw me'],
    role: 'expert visual prompt composer',
    must: ['subject', 'composition', 'lighting', 'style/medium', 'colour direction', 'aspect ratio', 'negative constraints'],
    tech: ['imageRecipe', 'constraints', 'examples'],
    fmt: 'image-prompt',
  },
  {
    id: 'image-editing', label: 'Image editing', group: 'media', media: 'image',
    kw: ['edit', 'retouch', 'inpaint', 'outpaint', 'remove background', 'upscale', 'colour grade', 'color grade', 'restore', 'mask', 'composite'],
    ph: ['edit this image', 'change the background', 'remove the object', 'make it look like', 'fix the photo'],
    role: 'image-editing prompt specialist',
    must: ['source image description', 'exact change requested', 'what must stay identical', 'output resolution'],
    tech: ['imageRecipe', 'constraints', 'verification'],
    fmt: 'image-prompt',
  },
  {
    id: 'video-generation', label: 'Video generation', group: 'media', media: 'video',
    kw: ['video', 'animation', 'animate', 'clip', 'sora', 'runway', 'veo', 'kling', 'pika', 'b-roll', 'footage', 'storyboard'],
    ph: ['generate a video', 'animate this', 'video prompt', 'short clip of', 'camera movement'],
    role: 'expert video prompt composer',
    must: ['shot list', 'camera movement', 'subject motion', 'lighting', 'audio plan', 'duration', 'continuity rules'],
    tech: ['videoRecipe', 'decomposition', 'constraints'],
    fmt: 'video-prompt',
  },
  {
    id: 'audio', label: 'Audio & music', group: 'media', media: 'audio',
    kw: ['audio', 'music', 'song', 'sound', 'soundtrack', 'podcast', 'voiceover', 'voice over', 'dubbing', 'mix', 'mixing', 'instrumental', 'melody'],
    ph: ['create music', 'background music', 'voice over for', 'podcast script', 'sound design'],
    role: 'audio producer and sound designer',
    must: ['genre/mood', 'duration', 'instrumentation or voice spec', 'usage context', 'loudness/format needs'],
    tech: ['role', 'constraints', 'structuredOutput'],
    fmt: 'structured-report',
  },
  {
    id: 'ui-ux', label: 'UI/UX design', group: 'product',
    kw: ['ui', 'ux', 'interface', 'wireframe', 'mockup', 'usability', 'user experience', 'design system', 'accessibility', 'a11y', 'responsive', 'typography'],
    ph: ['user interface', 'user experience', 'design a screen', 'improve usability', 'make it look good'],
    role: 'senior product designer',
    must: ['user and context', 'platform', 'constraints (brand/tech)', 'accessibility level', 'success metric'],
    tech: ['role', 'decomposition', 'multiPerspective', 'rubric'],
    fmt: 'document',
  },
  {
    id: 'website', label: 'Website creation', group: 'product',
    kw: ['website', 'webpage', 'landing', 'hosting', 'domain', 'wordpress', 'webflow', 'netlify', 'vercel', 'wix', 'shopify'],
    ph: ['web app', 'portfolio website', 'portfolio site', 'personal website', 'build a website', 'create a landing page', 'make a portfolio', 'website for my', 'build me a site', 'build me a website', 'dark mode', 'responsive', 'landing page'],
    role: 'full-stack web engineer and product designer',
    must: ['purpose and audience', 'pages/sections', 'tech constraints', 'responsive + accessibility bar', 'deployment target'],
    tech: ['role', 'decomposition', 'constraints', 'verification', 'edgeCases'],
    fmt: 'build-spec',
  },
  {
    id: 'app-development', label: 'App development', group: 'product',
    kw: ['app', 'android', 'ios', 'flutter', 'react native', 'swift', 'kotlin', 'mobile', 'desktop app', 'electron'],
    ph: ['build an app', 'mobile application', 'app idea', 'develop an app'],
    role: 'senior mobile application engineer',
    must: ['platform and versions', 'core features', 'data model', 'offline/permission behaviour', 'distribution target'],
    tech: ['role', 'decomposition', 'constraints', 'verification'],
    fmt: 'build-spec',
  },
  {
    id: 'game-dev', label: 'Game development', group: 'product',
    kw: ['game', 'gamedev', 'unity', 'unreal', 'godot', 'godot', 'player', 'level design', 'mechanic', 'mechanics', 'sprite', 'fps'],
    ph: ['make a game', 'game design', 'game mechanics', 'game idea'],
    role: 'game designer and gameplay engineer',
    must: ['genre and platform', 'core loop', 'scope limit', 'engine and version', 'asset constraints'],
    tech: ['role', 'decomposition', 'planExecute', 'constraints'],
    fmt: 'build-spec',
  },
  {
    id: 'automation', label: 'Automation', group: 'engineering',
    kw: ['automate', 'automation', 'script', 'workflow', 'zapier', 'make.com', 'n8n', 'cron', 'pipeline', 'trigger', 'webhook'],
    ph: ['automate this', 'save time by', 'connect these tools', 'no code automation', 'repeat task'],
    role: 'automation engineer',
    must: ['current manual process', 'tools available', 'trigger and schedule', 'failure handling', 'cost/limits'],
    tech: ['role', 'decomposition', 'toolUse', 'premortem'],
    fmt: 'build-spec',
  },
  {
    id: 'agent-design', label: 'AI agent design', group: 'ai',
    kw: ['agent', 'agentic', 'autonomous', 'orchestration', 'orchestrator', 'subagent', 'crewai', 'langgraph', 'mcp', 'function calling', 'planning loop'],
    ph: ['build an agent', 'ai agent', 'agent workflow', 'multi agent', 'autonomous workflow'],
    role: 'AI systems architect specialising in agentic workflows',
    must: ['goal', 'tools and permissions', 'state/memory', 'termination conditions', 'failure recovery', 'cost/step budget'],
    tech: ['agentic', 'decomposition', 'toolUse', 'premortem', 'verification'],
    fmt: 'agent-spec',
  },
  {
    id: 'ai-development', label: 'AI/ML development', group: 'ai',
    kw: ['ai', 'ml', 'machine learning', 'deep learning', 'neural', 'llm', 'model', 'training', 'dataset', 'fine-tune', 'finetune', 'embedding', 'rag', 'vector', 'pytorch', 'tensorflow', 'transformer'],
    ph: ['train a model', 'machine learning project', 'fine tune', 'build an ml', 'llm application'],
    role: 'machine learning engineer',
    must: ['problem framing (task type)', 'data availability', 'compute budget', 'evaluation metric', 'baseline'],
    tech: ['role', 'decomposition', 'extractAnalyzeGenerate', 'verification', 'rubric'],
    fmt: 'structured-report',
  },
  {
    id: 'prompt-engineering', label: 'Prompt engineering', group: 'ai',
    kw: ['prompt', 'prompting', 'system prompt', 'instructions', 'temperature', 'few-shot', 'chain of thought', 'jailbreak', 'prompt injection'],
    ph: ['improve this prompt', 'write a prompt', 'system prompt for', 'better prompt', 'prompt for chatgpt'],
    role: 'senior prompt engineer',
    must: ['target model', 'task and success criteria', 'output contract', 'failure modes to defend against'],
    tech: ['metaPrompt', 'rubric', 'redTeam', 'structuredOutput'],
    fmt: 'prompt',
  },
  {
    id: 'meta-prompting', label: 'Meta-prompting', group: 'ai',
    kw: ['meta', 'metaprompt', 'meta-prompt', 'prompt generator', 'prompt architect', 'reusable', 'template engine'],
    ph: ['prompt that creates prompts', 'generate a prompt generator', 'meta prompt', 'build a prompt system'],
    role: 'meta-prompt architect',
    must: ['reusable invocation contract', 'variable slots', 'quality bar for generated prompts'],
    tech: ['metaPrompt', 'decomposition', 'rubric'],
    fmt: 'prompt',
  },
  {
    id: 'brainstorming', label: 'Brainstorming', group: 'creative', creative: true,
    kw: ['brainstorm', 'ideas', 'idea', 'suggestions', 'possibilities', 'options', 'inspiration', 'concepts'],
    ph: ['give me ideas', 'brainstorm ideas', 'come up with', 'list some ideas', 'think of'],
    role: 'creative strategist who generates then filters',
    must: ['constraints on the solution space', 'quantity target', 'selection criteria'],
    tech: ['role', 'branchSelect', 'generationFiltering', 'multiPerspective'],
    fmt: 'bullets',
  },
  {
    id: 'simulation', label: 'Simulation & scenario', group: 'creative',
    kw: ['simulate', 'simulation', 'scenario', 'what if', 'war game', 'monte carlo', 'model the'],
    ph: ['simulate a scenario', 'what if i', 'run through the scenario', 'model how this plays out'],
    role: 'scenario modeller',
    must: ['starting conditions', 'rules that govern the simulation', 'number of runs/branches', 'what to report'],
    tech: ['role', 'branchSelect', 'selfConsistency', 'structuredOutput'],
    fmt: 'structured-report',
  },
  {
    id: 'roleplay', label: 'Roleplay & practice', group: 'creative',
    kw: ['roleplay', 'role play', 'pretend', 'act as', 'persona', 'character', 'practice conversation', 'mock'],
    ph: ['act as my', 'pretend you are', 'role play as', 'practice with me'],
    role: 'in-character simulator with an out-of-character coach mode',
    must: ['character/setting detail', 'in/out of character rules', 'difficulty', 'exit conditions'],
    tech: ['role', 'roleplay', 'rubric', 'fewShot'],
    fmt: 'roleplay',
  },
  {
    id: 'communication', label: 'Communication & messages', group: 'communication',
    kw: ['email', 'message', 'letter', 'reply', 'respond', 'apology', 'negotiate', 'negotiation', 'conversation', 'difficult', 'feedback', 'complaint'],
    ph: ['write an email', 'how do i tell', 'reply to this', 'say this politely', 'talk to my'],
    role: 'communication coach and professional writer',
    must: ['relationship and context', 'desired outcome', 'tone boundaries', 'what not to say'],
    tech: ['role', 'examples', 'constraints', 'branchSelect'],
    fmt: 'prose',
  },
  {
    id: 'devops', label: 'DevOps & infrastructure', group: 'engineering',
    kw: ['devops', 'docker', 'kubernetes', 'ci', 'cd', 'deploy', 'deployment', 'pipeline', 'terraform', 'aws', 'azure', 'gcp', 'nginx', 'linux', 'server', 'container'],
    ph: ['set up ci', 'deploy to', 'dockerise', 'dockerize', 'infrastructure as code', 'server setup'],
    role: 'site reliability / platform engineer',
    must: ['current environment and versions', 'constraints (cost/uptime/region)', 'secrets handling', 'rollback plan'],
    tech: ['role', 'decomposition', 'premortem', 'verification', 'edgeCases'],
    fmt: 'runbook',
  },
  {
    id: 'security-review', label: 'Security review', group: 'high-stakes', defensive: true,
    kw: ['security', 'vulnerability', 'penetration', 'pentest', 'owasp', 'exploit', 'hardening', 'cve', 'threat model', 'audit'],
    ph: ['security review', 'is this secure', 'find vulnerabilities', 'threat model', 'harden this'],
    role: 'application security engineer (defensive)',
    must: ['scope and authorisation', 'attack surface', 'finding severity model', 'remediation guidance'],
    tech: ['role', 'redTeam', 'premortem', 'verification', 'structuredOutput'],
    fmt: 'security-report',
  },
  {
    id: 'data-viz', label: 'Data visualisation', group: 'data',
    kw: ['chart', 'graph', 'dashboard', 'visualisation', 'visualization', 'plot', 'visual', 'infographic', 'matplotlib', 'chart.js', 'plotly'],
    ph: ['create a chart', 'visualise this', 'visualize data', 'dashboard for'],
    role: 'data visualisation designer',
    must: ['data structure', 'message the chart must convey', 'chart type constraint', 'accessibility/colour rules'],
    tech: ['role', 'constraints', 'structuredOutput', 'verification'],
    fmt: 'structured-report',
  },
  {
    id: 'spreadsheet', label: 'Spreadsheets & modelling', group: 'data',
    kw: ['spreadsheet', 'excel', 'google sheets', 'formula', 'pivot', 'googlesheets', 'worksheet', 'macro', 'vlookup', 'power query'],
    ph: ['excel formula', 'google sheets formula', 'build a spreadsheet', 'pivot table'],
    role: 'spreadsheet modelling expert',
    must: ['tool and version', 'data layout', 'expected result', 'whether formulas or values are wanted'],
    tech: ['role', 'examples', 'constraints', 'verification'],
    fmt: 'table',
  },
  {
    id: 'other', label: 'Other / unclassified', group: 'misc',
    kw: [], ph: [],
    role: 'expert assistant appropriate to the task',
    must: ['objective', 'success criteria'], tech: ['role', 'structuredOutput'],
    fmt: 'markdown',
  },
];

export const CATEGORY_INDEX = Object.fromEntries(TAXONOMY.map((t) => [t.id, t]));

export function categoriesByGroup() {
  const out = {};
  for (const t of TAXONOMY) (out[t.group] ||= []).push(t);
  return out;
}

/** Categories that imply the prompt will ingest untrusted third-party data. */
export const INGESTING_CATEGORIES = new Set([
  'research', 'web-research', 'academic', 'summarization', 'translation', 'editing',
  'data-analysis', 'document', 'legal', 'coding', 'debugging', 'security-review',
]);
